
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { ThemeContextProvider } from "@/context/themeContext";
import { PageContextProvider } from "@/context/pageContext";
import Navbar from "./components/navbar";
import { pages } from "./list_page";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
       <SessionProvider>
          <ThemeContextProvider>
            <PageContextProvider>
              <Navbar pages={pages} />
              <main className="flex-1 overflow-y-auto">{children}</main>
            </PageContextProvider>
          </ThemeContextProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
