import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ThemeContextProvider } from "@/context/themeContext";
import { PageContextProvider } from "@/context/pageContext";
import Layout from "./components/layout";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <PageContextProvider>
          <ThemeContextProvider>
           {children}
          </ThemeContextProvider>
        </PageContextProvider>
      </body>
    </html>
  );
}
